export const CURATED_TRACKS = [
  {
    id: 'billie-jean',
    title: 'Billie Jean',
    artist: 'Michael Jackson',
    searchQuery: 'Billie+Jean+Michael+Jackson',
    gradient: 'from-purple-400 to-pink-400',
  },
  {
    id: 'blinding-lights',
    title: 'Blinding Lights',
    artist: 'The Weeknd',
    searchQuery: 'Blinding+Lights+The+Weeknd',
    gradient: 'from-red-400 to-orange-400',
  },
  {
    id: 'starboy',
    title: 'Starboy',
    artist: 'The Weeknd',
    searchQuery: 'Starboy+The+Weeknd',
    gradient: 'from-teal-400 to-cyan-400',
  },
  {
    id: 'smooth-criminal',
    title: 'Smooth Criminal',
    artist: 'Michael Jackson',
    searchQuery: 'Michael Jackson Smooth Criminal',
    gradient: 'from-indigo-400 to-purple-500',
  },
  {
    id: 'bohemian-rhapsody',
    title: 'Bohemian Rhapsody',
    artist: 'Queen',
    searchQuery: 'Queen Bohemian Rhapsody',
    gradient: 'from-amber-400 to-rose-500',
  },
  {
    id: 'levitating',
    title: 'Levitating',
    artist: 'Dua Lipa',
    searchQuery: 'Dua Lipa Levitating',
    gradient: 'from-fuchsia-400 to-pink-500',
  },
  {
    id: 'bad-guy',
    title: 'bad guy',
    artist: 'Billie Eilish',
    searchQuery: 'Billie Eilish bad guy',
    gradient: 'from-emerald-400 to-teal-500',
  },
  {
    id: 'uptown-funk',
    title: 'Uptown Funk',
    artist: 'Mark Ronson ft. Bruno Mars',
    searchQuery: 'Mark Ronson Uptown Funk Bruno Mars',
    gradient: 'from-sky-400 to-blue-500',
  },
]
